spring.application.name=lab2
spring.datasource.url=jdbc:postgresql://localhost:5432/test_db
spring.datasource.password=test
spring.datasource.username=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.locale=en
spring.web.locale-resolver=fixed